version: "3"

# Builds you cannot really due without actual emulated architectures
services:
  armhf:
    #build:
    #  context: ./dockerfiles
    #  dockerfile: armhf
    # above built and pushed to below image
    image: diginc/multiarch-deb-debootstrap:armhf-musl-jessie
    volumes:
      - './:/build'
